-- ====================================================================
-- Müllerhof CMS – Seed aller bestehenden Seitentexte
-- Automatisch aus den HTML-Dateien extrahiert.
-- Im Supabase SQL Editor ausführen (einmalig).
-- ====================================================================

INSERT INTO public.cms_sections (page_slug, section_key, kind, label, content, sort_order) VALUES
('index', 'intro_kicker', 'text', 'Intro – Kicker', 'Willkommen im Müllerhof', 1),
('index', 'intro_usp', 'html', 'Intro – Zitat / USP', '<em data-cms="index:intro_usp">„Der Müllerhof bringt Generationen zusammen und macht Gemeinschaft in Frick erlebbar.“</em>', 2),
('index', 'section_header_h2', 'text', 'Section – Headline', 'Wo du dich heute zuhause fühlst.', 3),
('index', 'section_header_h2_2', 'html', 'Section – Headline (2)', 'Sechs Räume.<br/>Unzählige Anlässe.', 4),
('index', 'section_header_lead', 'text', 'Section – Lead', 'Drei Stimmungen, ein gemeinsames Dach – jede Ecke des Müllerhofs erzählt eine eigene Geschichte.', 5),
('index', 'section_header_lead_2', 'text', 'Section – Lead (2)', 'Vom intimen Familienfest im Gewölbekeller bis zur Hochzeit auf der Terrasse – wir haben den passenden Raum für jeden Anlass.', 6),
('index', 'split_h2', 'html', 'Split – Headline', 'Vom Bauernhaus<br/>zum Begegnungsort.', 7),
('index', 'split_h2_2', 'html', 'Split – Headline (2)', 'Wissen teilen.<br/>Geschichten austauschen.', 8),
('index', 'split_h2_3', 'html', 'Split – Headline (3)', 'Wir suchen Menschen,<br/>die mitgestalten wollen.', 9),
('index', 'split_p', 'text', 'Split – Absatz', 'Ursprünglich Bauernhaus, 1984 als Betriebskantine der Jakob Müller AG eröffnet, ab Ende der 2000er-Jahre auch für externe Gäste geöffnet. 2019 umfassend saniert – heute mit sieben Hotelzimmern und einem klaren Versprechen: Gastfreundschaft, lokale Küche und generationenübergreifende Begegnungen.', 10),
('index', 'split_p_2', 'text', 'Split – Absatz (2)', 'Mit Workshops, Jass-Nachmittagen, Sonntagsbrunches und gemeinsamen Veranstaltungen schaffen wir Raum, in dem Jung und Alt voneinander lernen. Vom Familienevent bis zum Generationenfest – im Müllerhof findet jede Generation ihren Platz.', 11),
('index', 'split_p_3', 'text', 'Split – Absatz (3)', 'Sucht deine Grossmutter noch einen Job? Bist du Koch mit Leidenschaft? Servicekraft mit Herz? Im Müllerhof suchen wir Menschen jeden Alters, die unseren Treffpunkt mit uns gestalten wollen. Auch Blindbewerbungen sind willkommen.', 12),
('index', 'bereich_card_title', 'text', 'Bereich-Card – Titel', 'Frühstück, Znüni, Mittag.', 13),
('index', 'bereich_card_title_2', 'text', 'Bereich-Card – Titel (2)', 'Apéro, Austausch, Ankommen.', 14),
('index', 'bereich_card_title_3', 'text', 'Bereich-Card – Titel (3)', 'À la carte, klassisch, gepflegt.', 15),
('index', 'bereich_card_text', 'text', 'Bereich-Card – Text', 'Der traditionelle Hauptbereich – unkomplizierte, alltagsnahe Gastronomie mit Frühstücksbuffet, Znüni und Mittagstisch. Sonntags Brunch.', 16),
('index', 'bereich_card_text_2', 'text', 'Bereich-Card – Text (2)', 'Der gemütliche Begegnungsbereich – für entspannte Aufenthalte, gesellige Apéros und gemeinsame Momente mit hausgemachten Spezialitäten.', 17),
('index', 'bereich_card_text_3', 'text', 'Bereich-Card – Text (3)', 'Der bediente Restaurantbereich mit gutbürgerlicher, regional verankerter Küche und sorgfältig zubereiteten Vor-, Haupt- und Dessertgängen.', 18),
('restaurant', 'hero_sub', 'text', 'Hero – Untertitel', 'Restaurant', 1),
('restaurant', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Drei Bereiche.<br/>Ein Wohnzimmer.', 2),
('restaurant', 'hero_tagline', 'text', 'Hero – Tagline', 'Wo Begegnung zuhause ist.', 3),
('restaurant', 'intro_kicker', 'text', 'Intro – Kicker', 'Restauration', 4),
('restaurant', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Reservation', 5),
('restaurant', 'intro_headline', 'html', 'Intro – Headline', 'Vielseitiges Angebot.<br/>Stimmiges Gesamtbild.', 6),
('restaurant', 'intro_lead', 'html', 'Intro – Lead-Text', 'Mit den drei Gastronomiebereichen <strong>alte Höfli</strong>, <strong>Wohnzimmer</strong> und <strong>Stübli</strong> entsteht ein vielseitiges Angebot mit unterschiedlichen Stimmungen und Nutzungsmöglichkeiten – und doch ein einheitliches und stimmiges Gesamtbild. Der Fokus liegt konsequent auf regionalen Produkten und einer traditionellen Küche.', 7),
('restaurant', 'section_header_h2', 'text', 'Section – Headline', 'Alle Karten auf einen Blick.', 8),
('restaurant', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Tisch reservieren.', 9),
('restaurant', 'section_header_lead', 'text', 'Section – Lead', 'Speisen, Getränke, Wein – alle Karten unserer drei Bereiche zum Direkt-Ansehen.', 10),
('restaurant', 'section_header_lead_2', 'text', 'Section – Lead (2)', 'Wir freuen uns auf dich. Reserviere telefonisch, per E-Mail oder über unser Formular.', 11),
('restaurant', 'split_h2', 'text', 'Split – Headline', 'Frühstück. Znüni. Mittag.', 12),
('restaurant', 'split_h2_2', 'text', 'Split – Headline (2)', 'Apéro. Austausch. Ankommen.', 13),
('restaurant', 'split_h2_3', 'text', 'Split – Headline (3)', 'À la carte. Klassisch. Gepflegt.', 14),
('restaurant', 'split_p', 'text', 'Split – Absatz', 'Das alte Höfli bildet den traditionellen Hauptbereich des Hauses und steht für unkomplizierte, alltagsnahe Gastronomie. Es ist der tägliche erste Anlaufpunkt für Frühstück, Znüni und Mittagsverpflegung.', 15),
('restaurant', 'split_p_2', 'text', 'Split – Absatz (2)', 'Das Frühstücksangebot umfasst ein grosszügiges Buffet mit regionalen Produkten, Früchten, Käse, Brot und Gebäck sowie Birchermüesli, ergänzt durch Eierspeisen à la carte. Am Sonntag verwandelt sich das alte Höfli in einen Brunch-Treffpunkt mit grosszügigem Buffet aus regionalen Produkten.', 16),
('restaurant', 'split_p_3', 'text', 'Split – Absatz (3)', 'Das Wohnzimmer ist der gemütliche Begegnungsbereich des Müllerhofs und steht für entspannte Aufenthalte, gesellige Apéros und gemeinsame Momente. Die Gäste gelangen über das alte Höfli oder den Haupteingang in diesen bedienten Bereich.', 17),
('restaurant', 'split_p_4', 'text', 'Split – Absatz (4)', 'Das Angebot umfasst hausgemachte Spezialitäten und regionale Produkte – perfekt für den Apéro nach Feierabend, ein gemütliches Treffen mit Freunden oder einfach um anzukommen.', 18),
('restaurant', 'split_p_5', 'text', 'Split – Absatz (5)', 'Das Stübli bildet den klassischen bedienten Restaurantbereich mit À-la-carte-Angebot und gepflegtem Ambiente. Es ist sowohl über Mittag als auch am Abend geöffnet und richtet sich an Gäste, die ein ruhigeres und persönlich betreutes Restauranterlebnis suchen.', 19),
('restaurant', 'split_p_6', 'text', 'Split – Absatz (6)', 'Die Küche setzt auf gutbürgerliche, regional verankerte Produkte und klassische Zubereitungen mit modernem Anspruch. Das Angebot umfasst sorgfältig zubereitete Vorspeisen, Hauptgänge und hausgemachte Desserts.', 20),
('hotel', 'hero_sub', 'text', 'Hero – Untertitel', 'Hotel', 1),
('hotel', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Sieben Zimmer.<br/>Ein Zuhause.', 2),
('hotel', 'hero_tagline', 'text', 'Hero – Tagline', 'Übernachten im Müllerhof.', 3),
('hotel', 'intro_kicker', 'text', 'Intro – Kicker', 'Hotel im Müllerhof', 4),
('hotel', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Unsere Zimmer', 5),
('hotel', 'intro_kicker_3', 'text', 'Intro – Kicker (3)', 'Buchen', 6),
('hotel', 'intro_headline', 'html', 'Intro – Headline', 'Ankommen. Wohlfühlen.<br/>Bleiben.', 7),
('hotel', 'intro_headline_2', 'text', 'Intro – Headline (2)', 'Zimmer reservieren.', 8),
('hotel', 'intro_lead', 'text', 'Intro – Lead-Text', 'Sieben modern sanierte Hotelzimmer im Herzen von Frick – ruhig gelegen, mit Aargauer Charme und allem, was du für einen guten Aufenthalt brauchst. Ideal für Geschäftsreisende, Wochenendbesucher und Seminargäste.', 9),
('hotel', 'intro_lead_2', 'text', 'Intro – Lead-Text (2)', 'Buche dein Zimmer direkt – per Formular, Telefon oder E-Mail. Online-Buchung über unser System folgt in Kürze.', 10),
('hotel', 'section_header_h2', 'text', 'Section – Headline', 'Sieben Zimmer · Sieben Geschichten.', 11),
('hotel', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Was du erwarten kannst.', 12),
('hotel', 'section_header_lead', 'text', 'Section – Lead', '[ Inhalte folgen vom Müllerhof ]', 13),
('events', 'hero_sub', 'text', 'Hero – Untertitel', 'Events &amp; Veranstaltungen', 1),
('events', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Anlässe<br/>mit Wirkung.', 2),
('events', 'hero_tagline', 'text', 'Hero – Tagline', 'Vom Familienfest bis zur Hochzeit.', 3),
('events', 'intro_kicker', 'text', 'Intro – Kicker', 'Events im Müllerhof', 4),
('events', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Specials ab August 2027', 5),
('events', 'intro_kicker_3', 'text', 'Intro – Kicker (3)', 'Eventgalerie', 6),
('events', 'intro_headline', 'text', 'Intro – Headline', 'Gemeinschaft erlebbar machen.', 7),
('events', 'intro_lead', 'text', 'Intro – Lead-Text', 'Auf Events legen wir grossen Wert: Sie fördern Verbundenheit und Gemeinschaft und tragen unsere Werte nach aussen. Veranstaltungen bringen Menschen zusammen und machen Gastfreundschaft, Authentizität und gelebte Gemeinschaft erlebbar. Workshops, Kurse und gemeinsame Aktivitäten schaffen Raum für Austausch zwischen den Generationen.', 8),
('events', 'section_header_h2', 'text', 'Section – Headline', 'Drei Arten von Anlässen.', 9),
('events', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Jede Woche bei uns.', 10),
('events', 'section_header_h2_3', 'text', 'Section – Headline (3)', 'Was läuft im Müllerhof?', 11),
('events', 'section_header_h2_4', 'text', 'Section – Headline (4)', 'Bereits durchgeführte Anlässe.', 12),
('events', 'section_header_lead', 'text', 'Section – Lead', 'Wir starten im August 2027 durch! Unsere besonderen Anlässe ab Eröffnung – Saison-Highlights, Themen-Dinner und Workshops.', 13),
('events', 'section_header_lead_2', 'text', 'Section – Lead (2)', 'Ein Blick in unsere Eventgeschichte – von intimen Familienfesten bis zu grossen Feiern.', 14),
('events', 'split_h2', 'html', 'Split – Headline', 'Feiern unter<br/>freiem Himmel.', 15),
('events', 'split_p', 'text', 'Split – Absatz', 'Unser grosser Garten mit Rasenfläche ist die perfekte Bühne für deinen Anlass: Hochzeiten unter freiem Himmel, Sommer-Afterworks, Familienfeste oder Garten-Apéros – mit viel Platz, viel Grün und der ganzen Natur drumherum.', 16),
('events', 'split_p_2', 'text', 'Split – Absatz (2)', 'Auf Anfrage kombinieren wir Garten, Terrasse und Innenräume zu deinem perfekten Event-Setup.', 17),
('events', 'bereich_card_title', 'text', 'Bereich-Card – Titel', 'Hochzeiten, Geburtstage, Familienfeste.', 18),
('events', 'bereich_card_title_2', 'text', 'Bereich-Card – Titel (2)', 'Sonntagsbrunch, Jass, Workshops.', 19),
('events', 'bereich_card_title_3', 'text', 'Bereich-Card – Titel (3)', 'Specials &amp; Workshops.', 20),
('events', 'bereich_card_text', 'text', 'Bereich-Card – Text', 'Vom Gewölbekeller über das Stübli bis zur Terrasse – wir haben den passenden Raum für deinen Anlass. Auch Feiern nach kirchlichen Zeremonien sind herzlich willkommen.', 21),
('events', 'bereich_card_text_2', 'text', 'Bereich-Card – Text (2)', 'Wöchentlicher Sonntagsbrunch, monatlicher Jass-Nachmittag und saisonale Angebote – für Familien, Freunde und alle Generationen.', 22),
('events', 'bereich_card_text_3', 'text', 'Bereich-Card – Text (3)', 'Im Gewölbekeller gibt''s spezielle Dining-Erlebnisse über das Jahr verteilt. Im alte Höfli finden Familien- und Kinderaktivitäten statt. Saisonale Kulinarik immer dabei.', 23),
('seminare', 'hero_sub', 'text', 'Hero – Untertitel', 'Seminare &amp; Workshops', 1),
('seminare', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Tagen.<br/>Lernen. Wirken.', 2),
('seminare', 'hero_tagline', 'text', 'Hero – Tagline', 'Im obersten Stock des Müllerhofs.', 3),
('seminare', 'intro_kicker', 'text', 'Intro – Kicker', 'Seminarraum', 4),
('seminare', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Anfrage', 5),
('seminare', 'intro_headline', 'html', 'Intro – Headline', 'Vollausgestattet.<br/>Praxisnah.', 6),
('seminare', 'intro_headline_2', 'text', 'Intro – Headline (2)', 'Dein Seminar im Müllerhof.', 7),
('seminare', 'intro_lead', 'text', 'Intro – Lead-Text', 'Im obersten Stock des Müllerhofs befindet sich ein vollausgestatteter Seminarraum mit verschiedenen Bestuhlungsvarianten und einer Kaffeeecke ausserhalb des Raumes. Zur Grundausstattung gehören Beamer, WLAN, Flipchart, Whiteboard, Klimaanlage und Moderationsmaterial.', 8),
('seminare', 'intro_lead_2', 'text', 'Intro – Lead-Text (2)', 'Anfrage senden, Angebot erhalten, Workshop durchführen – wir machen''s einfach.', 9),
('seminare', 'split_h2', 'text', 'Split – Headline', 'Alles, was dein Seminar braucht.', 10),
('community', 'hero_sub', 'text', 'Hero – Untertitel', 'Community', 1),
('community', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Erlebnisse teilen.<br/>Erinnerungen schaffen.', 2),
('community', 'hero_tagline', 'text', 'Hero – Tagline', 'Deine Müllerhof-Stories.', 3),
('community', 'intro_kicker', 'text', 'Intro – Kicker', 'Müllerhof Community', 4),
('community', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Eigenen Post teilen', 5),
('community', 'intro_kicker_3', 'text', 'Intro – Kicker (3)', 'Was die Community sagt', 6),
('community', 'intro_headline', 'text', 'Intro – Headline', 'Erzähl uns von deinem Müllerhof-Moment.', 7),
('community', 'intro_lead', 'text', 'Intro – Lead-Text', 'Hier können unsere Gäste ihre Erlebnisse teilen: vom gemütlichen Sonntagsbrunch, vom Hochzeitstanz im Garten, vom Jass-Abend mit den Enkeln. Schreib einen kurzen Post, lade ein Foto hoch und gib uns Sterne – wir freuen uns auf deine Geschichte!', 8),
('community', 'section_header_h2', 'text', 'Section – Headline', 'Was war dein Müllerhof-Erlebnis?', 9),
('community', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Eindrücke aus dem Müllerhof.', 10),
('community', 'section_header_lead', 'text', 'Section – Lead', 'Geschichten unserer Gäste – sortiert nach Aktualität.', 11),
('ueber-uns', 'hero_sub', 'text', 'Hero – Untertitel', 'Über uns', 1),
('ueber-uns', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Von Frick.<br/>Für Frick.', 2),
('ueber-uns', 'hero_tagline', 'text', 'Hero – Tagline', 'Eine Geschichte von Begegnung.', 3),
('ueber-uns', 'intro_kicker', 'text', 'Intro – Kicker', 'Hauptbotschaft', 4),
('ueber-uns', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Unsere Geschichte', 5),
('ueber-uns', 'intro_headline', 'html', 'Intro – Headline', '„Das Wohnzimmer von Frick –<br/>wo Begegnung zuhause ist."', 6),
('ueber-uns', 'intro_lead', 'text', 'Intro – Lead-Text', 'Der Müllerhof verbindet Gastronomie, Gemeinschaft und modernes Dorfleben zu einem Ort, an dem Menschen verschiedener Generationen zusammenkommen. Im Mittelpunkt stehen echte Begegnungen, der Austausch von Wissen und Erfahrungen zwischen Jung und Alt sowie das Gefühl von zuhause.', 7),
('ueber-uns', 'section_header_h2', 'text', 'Section – Headline', 'Vom Bauernhaus zum Begegnungsort.', 8),
('ueber-uns', 'split_h2', 'text', 'Split – Headline', 'Gemeinschaft wieder selbstverständlich machen.', 9),
('ueber-uns', 'split_h2_2', 'text', 'Split – Headline (2)', 'Von Frick. Für Frick.', 10),
('ueber-uns', 'split_h2_3', 'text', 'Split – Headline (3)', 'Mittendrin im Fricktal.', 11),
('ueber-uns', 'split_p', 'text', 'Split – Absatz', 'Familien, Freundesgruppen, Seniorinnen und Senioren, junge Erwachsene sowie Unternehmen aus Frick und der Region – sie alle sollen hier einen Ort finden, an dem sie zusammenkommen, verweilen und gemeinsame Erlebnisse teilen können.', 12),
('ueber-uns', 'split_p_2', 'text', 'Split – Absatz (2)', 'Unter dem Leitgedanken „Das Wohnzimmer von Frick" soll der Müllerhof zu einem zentralen Treffpunkt werden, an dem Begegnungen gefördert, Erinnerungen geschaffen und das Dorfleben neu belebt werden.', 13),
('ueber-uns', 'split_p_3', 'text', 'Split – Absatz (3)', 'Der Müllerhof verbindet Menschen, Generationen und Geschichten und schafft Raum für Begegnung, Austausch und gemeinsame Erlebnisse.', 14),
('ueber-uns', 'split_p_4', 'text', 'Split – Absatz (4)', 'Durch regionale Verbundenheit, authentische Gastfreundschaft und moderne Hospitality entsteht ein lebendiger Treffpunkt, an dem Begegnung zuhause ist.', 15),
('ueber-uns', 'split_p_5', 'text', 'Split – Absatz (5)', 'Der Müllerhof befindet sich an der Schulstrasse 11 in Frick, einer Kleinstadt im Fricktal im Kanton Aargau. Die Gemeinde liegt im westlichen Aargau, eingebettet zwischen dem Jura im Norden und dem Rhein im Süden.', 16),
('ueber-uns', 'split_p_6', 'text', 'Split – Absatz (6)', 'Über die Autobahn A3 sowie den Bahnhof Frick sind wir gut erreichbar. Der Standort liegt direkt auf dem Firmengelände der Jakob Müller AG, in unmittelbarer Nähe zum Ortszentrum.', 17),
('karriere', 'hero_sub', 'text', 'Hero – Untertitel', 'Karriere', 1),
('karriere', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Wir suchen Menschen,<br/>die mitgestalten wollen.', 2),
('karriere', 'hero_tagline', 'text', 'Hero – Tagline', 'Für jede Generation.', 3),
('karriere', 'intro_kicker', 'text', 'Intro – Kicker', 'Müllerhof – das Wohnzimmer von Frick', 4),
('karriere', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Offene Stellen', 5),
('karriere', 'intro_kicker_3', 'text', 'Intro – Kicker (3)', 'Bewerbungsformular', 6),
('karriere', 'intro_headline', 'text', 'Intro – Headline', 'Wo Begegnung zuhause ist.', 7),
('karriere', 'intro_lead', 'html', 'Intro – Lead-Text', 'Du möchtest Generationen zusammenbringen und einen Ort mitgestalten, wo sich Menschen zuhause fühlen? Du hast eine Grossmutter, die eine spannende Abwechslung im Alltag sucht und aktiv mitwirken möchte? <strong>Dann bist du im Müllerhof genau richtig!</strong>', 8),
('karriere', 'intro_lead_2', 'text', 'Intro – Lead-Text (2)', 'Zur Verstärkung unseres Teams suchen wir engagierte Mitarbeitende. Der Müllerhof steht für ehrliche Gastfreundschaft, lokale Küche und generationenübergreifende Begegnungen. Mit unserem traditionellen und familiären Gastronomiekonzept schaffen wir einen Treffpunkt für Familien, regionale Gäste, Hotelgäste und alle, die echte Gastfreundschaft schätzen.', 9),
('karriere', 'section_header_h2', 'text', 'Section – Headline', 'Mehr als nur ein Job.', 10),
('karriere', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Wir suchen.', 11),
('karriere', 'section_header_h2_3', 'text', 'Section – Headline (3)', 'Bewirb dich direkt.', 12),
('karriere', 'section_header_lead', 'text', 'Section – Lead', 'Aktuelle Positionen im Müllerhof. Du findest deine Stelle nicht? Bewirb dich blind – wir freuen uns auf dich.', 13),
('karriere', 'section_header_lead_2', 'html', 'Section – Lead (2)', 'Sende uns deine Bewerbung. Oder kontaktiere Torsten Stobbe direkt unter <a href="mailto:info@muellerhof.ch" style="color: var(--c-brown); font-weight: 700;">info@muellerhof.ch</a>.', 14),
('karriere', 'split_h2', 'text', 'Split – Headline', 'Wir freuen uns auf deine Bewerbung!', 15),
('karriere', 'split_p', 'text', 'Split – Absatz', 'Bist du bereit, den Müllerhof gemeinsam mit uns neu zu gestalten und Teil eines herzlichen, motivierten Teams zu werden? Dann freuen wir uns auf deine Bewerbung!', 16),
('karriere', 'split_p_2', 'html', 'Split – Absatz (2)', '<strong>Ansprechperson:</strong><br/>Torsten Stobbe · Betriebsleiter Müllerhof<br/><a href="mailto:info@muellerhof.ch" style="color: var(--c-brown); font-weight: 700;">info@muellerhof.ch</a><br/>Müllerhof · Schulstrasse 11 · 5070 Frick AG', 17),
('karriere', 'split_p_3', 'text', 'Split – Absatz (3)', 'Wir freuen uns darauf, dich kennenzulernen!', 18),
('kontakt', 'hero_sub', 'text', 'Hero – Untertitel', 'Kontakt', 1),
('kontakt', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Schreib uns.<br/>Ruf uns an.', 2),
('kontakt', 'hero_tagline', 'text', 'Hero – Tagline', 'Wir freuen uns auf dich.', 3),
('kontakt', 'intro_kicker', 'text', 'Intro – Kicker', 'Erreichbarkeit', 4),
('kontakt', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Anfahrt', 5),
('kontakt', 'intro_kicker_3', 'text', 'Intro – Kicker (3)', 'Schreib uns direkt', 6),
('kontakt', 'intro_headline', 'text', 'Intro – Headline', 'Allgemeine Anfrage.', 7),
('kontakt', 'intro_lead', 'text', 'Intro – Lead-Text', 'Du hast eine Frage, einen Vorschlag oder möchtest einfach Hallo sagen?', 8),
('kontakt', 'section_header_h2', 'text', 'Section – Headline', 'Wie du uns erreichst.', 9),
('kontakt', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Hierher findest du.', 10),
('kontakt', 'section_header_lead', 'text', 'Section – Lead', 'Direkt auf dem Firmengelände der Jakob Müller AG, in der Nähe vom Ortszentrum Frick. Bahnhof Frick und Autobahn A3 in wenigen Minuten erreichbar.', 11),
('kooperationen', 'hero_sub', 'text', 'Hero – Untertitel', 'Kooperationen', 1),
('kooperationen', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Gemeinsam<br/>für Frick.', 2),
('kooperationen', 'hero_tagline', 'text', 'Hero – Tagline', 'Partner, die uns stärken.', 3),
('kooperationen', 'intro_kicker', 'text', 'Intro – Kicker', 'Unsere Partner', 4),
('kooperationen', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Werde Partner', 5),
('kooperationen', 'intro_headline', 'text', 'Intro – Headline', 'Begegnung braucht ein Netzwerk.', 6),
('kooperationen', 'intro_headline_2', 'text', 'Intro – Headline (2)', 'Lust auf Zusammenarbeit?', 7),
('kooperationen', 'intro_lead', 'text', 'Intro – Lead-Text', 'Der Müllerhof lebt von Zusammenarbeit. Mit lokalen Vereinen, sozialen Einrichtungen und regionalen Lieferanten gestalten wir Frick gemeinsam – generationenübergreifend und mit dem Herz am rechten Fleck.', 8),
('kooperationen', 'intro_lead_2', 'text', 'Intro – Lead-Text (2)', 'Du bist Verein, Institution, lokaler Produzent oder Unternehmen aus der Region und möchtest mit dem Müllerhof zusammenarbeiten? Wir freuen uns auf deine Anfrage.', 9),
('kooperationen', 'split_h2', 'html', 'Split – Headline', 'Älterwerden im Fricktal &amp;<br/>Alterszentrum Bruggbach.', 10),
('kooperationen', 'split_h2_2', 'text', 'Split – Headline (2)', 'Verein Älterwerden im Fricktal.', 11),
('kooperationen', 'split_p', 'text', 'Split – Absatz', '„Älterwerden im Fricktal" ist eine regionale Plattform, die ältere Menschen informiert, vernetzt und ihnen Angebote zugänglich macht. Das Alterszentrum Bruggbach ist eine wichtige Institution im Fricktal – Bewohnerinnen und Bewohner sind regelmässig im Müllerhof zu Gast und Teil unserer Gemeinschaft.', 12),
('kooperationen', 'split_p_2', 'text', 'Split – Absatz (2)', 'Gemeinsam mit beiden Partnern entwickeln wir den digitalen Fahr- und Gemeinschaftsservice, der es älteren Menschen ermöglicht, einfach am gesellschaftlichen Leben teilzunehmen.', 13),
('kooperationen', 'split_p_3', 'text', 'Split – Absatz (3)', 'Der Verein VAOF engagiert sich für die Lebensqualität älterer Menschen in der Region. Als Freiwilligenverein bringt er Menschen zusammen – ehrenamtlich, niederschwellig, mit viel Herzblut. Der Müllerhof unterstützt die Arbeit des Vereins als Veranstaltungspartner und Treffpunkt.', 14),
('galerie', 'hero_sub', 'text', 'Hero – Untertitel', 'Galerie', 1),
('galerie', 'hero_claim', 'html', 'Hero – Hauptclaim', 'Bilder, die<br/>Geschichten erzählen.', 2),
('galerie', 'hero_tagline', 'text', 'Hero – Tagline', 'Räume, Anlässe, Gemeinschaft.', 3),
('galerie', 'intro_kicker', 'text', 'Intro – Kicker', 'Räume', 4),
('galerie', 'intro_kicker_2', 'text', 'Intro – Kicker (2)', 'Anlässe', 5),
('galerie', 'intro_kicker_3', 'text', 'Intro – Kicker (3)', 'Aktualitätenschau', 6),
('galerie', 'intro_headline', 'html', 'Intro – Headline', 'Was läuft in Frick<br/>und im Müllerhof?', 7),
('galerie', 'intro_lead', 'text', 'Intro – Lead-Text', 'Aktuelle Geschichten, kommende Events, kleine Highlights aus dem Müllerhof-Alltag und dem Dorfleben in Frick. Hier sammeln wir, was in der Region passiert.', 8),
('galerie', 'intro_lead_2', 'html', 'Intro – Lead-Text (2)', '<em>Die Aktualitätenschau wird laufend ergänzt – schau regelmässig vorbei.</em>', 9),
('galerie', 'section_header_h2', 'text', 'Section – Headline', 'Unsere Räumlichkeiten.', 10),
('galerie', 'section_header_h2_2', 'text', 'Section – Headline (2)', 'Events und Begegnungen.', 11)
ON CONFLICT (page_slug, section_key) DO UPDATE SET
  content    = EXCLUDED.content,
  label      = EXCLUDED.label,
  kind       = EXCLUDED.kind,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
